version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: ./gradlew build test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
